name: Build and push to WKT registry ScalarGIS Server core image (latest)

on:
  push:
    branch: [ new-actions ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      id: build_image
      run: docker build . --tag registry.wkt.pt:5000/wkt/scalargis-server:latest

    - name: Login to WKT registry
      id: login_registry
      run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSW }} registry.wkt.pt:5000

    - name: Push to WKT registry
      id: push_image
      run: docker push registry.wkt.pt:5000/wkt/scalargis-server:latest
